from constants import SECRET_KEY, DATABASE_URI, MAIL_SETTINGS

class Config:
    SECRET_KEY = SECRET_KEY
    SQLALCHEMY_DATABASE_URI = DATABASE_URI
    SQLALCHEMY_TRACK_MODIFICATIONS = False

    MAIL_SERVER = MAIL_SETTINGS["MAIL_SERVER"]
    MAIL_PORT = MAIL_SETTINGS["MAIL_PORT"]
    MAIL_USE_TLS = MAIL_SETTINGS["MAIL_USE_TLS"]
    MAIL_USERNAME = MAIL_SETTINGS["MAIL_USERNAME"]
    MAIL_PASSWORD = MAIL_SETTINGS["MAIL_PASSWORD"]
    MAIL_DEFAULT_SENDER = MAIL_SETTINGS["MAIL_DEFAULT_SENDER"]

    POSTS_PER_PAGE = 10  # pagination
